<a href="https://colab.research.google.com/github/timmao78/git_demo/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [6]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#reshape and view
my_torch1 = my_torch.reshape(2,5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch2 = my_torch.view(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
#with reshape and view, they will update
my_torch[1] = 4141
my_torch

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [14]:
my_torch1

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [16]:
my_torch2

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [21]:
#slices
my_torch3 = my_torch.reshape(5,2)
my_torch3

tensor([[   0, 4141],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [23]:
my_torch3[:,1]

tensor([4141,    3,    5,    7,    9])

In [24]:
my_torch3[0,:]

tensor([   0, 4141])

In [25]:
my_torch3[:,1:]

tensor([[4141],
        [   3],
        [   5],
        [   7],
        [   9]])