<a href="https://colab.research.google.com/github/timmao78/git_demo/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

In [8]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [9]:
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [10]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [11]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [12]:
torch.sub(tensor_a,tensor_b)

tensor([-4, -4, -4, -4])

In [13]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [14]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [15]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [16]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [18]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [19]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [20]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [21]:
tensor_a += tensor_b
tensor_a

tensor([ 6,  8, 10, 12])